### ISSUE TITLE
[Bug] Translations

### ISSUE THREAD

**Issue by 510stefania** [rodekruis/social-media-listening#54]
During S17 we faced translations problems in HUN.
We used the Google sheet turn around,but translation were bad with the result that it took us more time and also stakeholder noticed that the translation wasn't good as usual

Please let's make sure that in S18 all countries are correctly translated and if not, let's fix it / re-run the scrape, because the turn around is not good solution.

**Comment by jmargutt** [comment]
No issues observed for HUN in the last scrape (08/21-09/04), putting it in review for @littlecrow86 to confirm.

**Comment by jmargutt** [comment]
@p-phung did you understand what was the issue?

**Comment by jmargutt** [comment]
@510stefania I understood that this is solved, if so pls close.

**Comment by p-phung** [comment]
It is suspected that the translation API were overloaded because data of multiple countries was requested to translate all at the same time.

When running the translation (via classification engine) one country by one, this issue is no longer there.

__Solution:__ wait before requesting classification for a new countries, like 30 min or more. This allows the translator to digest all the messages and avoid the missing translation issue.

**Comment by p-phung** [comment]
@510stefania  this now can be closed if you agree

**Comment by jmargutt** [comment]
@jmargutt to check if the API quota can be increased

**Comment by 510stefania** [comment]
For @littlecrow86 @ekaterina for requests:
- WF : request as soon they come in 
- messages : do not request all at once but request 1 country - wait a bit - request another country

**Comment by jmargutt** [comment]
[we cannot increase the translator quota without paying a crazy amount of money](https://learn.microsoft.com/en-us/azure/ai-services/translator/service-limits#character-limits-per-hour). We'll have to live with this.
